export const ADD_WORK = 'WORKS/ADD_WORK';
export const ADD_WORK_ERROR = 'WORKS/ADD_WORK_ERROR';
export const ADD_WORK_SUCCESS = 'WORKS/ADD_WORK_SUCCESS';
export const ADD_WORK_REQUESTED = 'WORKS/ADD_WORK_REQUESTED';

export const FETCH_WORKS = 'WORKS/FETCH_WORKS';
export const FETCH_WORKS_ERROR = 'WORKS/FETCH_WORKS_ERROR';
export const FETCH_WORKS_SUCCESS = 'WORKS/FETCH_WORKS_SUCCESS';
export const FETCH_WORKS_REQUESTED = 'WORKS/FETCH_WORKS_REQUESTED';

